#!/usr/bin/env python3
"""Build the dorsal and ventral 8-contact-lead variants of NBF_RADO-SCS.FCStd.

Each variant is a byte copy of the base document plus the nine STLs generated by
make_scs_lead.py (8 contacts + 1 insulator) from
src/freecad/generated_leads/<variant>_z110_8c/.

The lead STLs are already in the base model's coordinate frame -- make_scs_lead.py
swept them along the measured epidural centreline, and the placement was checked
at 100% of sampled vertices inside epidural fat and 0% in dura -- so they are
imported with NO transform of any kind. Anything that moved them would silently
invalidate that check.

RADO's own 4-contact DRG lead is DELETED from each variant, before the study
lead is imported. Per Mohamed: "I don't see the point of hiding them they don't
belong there!" -- and it is the right call for the physics, not just for the
tree. A variant exists to model ONE lead. A second lead left in the geometry is
not merely untidy: Simpleware/Gmsh would mesh it, the FEM solve would treat four
platinum cylinders and an insulator sheath as conductors sitting in the field a
few millimetres off the cord, and the resulting potentials -- and every axon
threshold computed from them -- would be wrong. Hiding a body (Visibility =
False) changes nothing about any of that; it only stops FreeCAD drawing it.

The BASE document, NBF_RADO-SCS.FCStd, keeps RADO's lead untouched. That is the
published model, and this script never writes to it -- it copies it.

Deleting first, then importing, is also what keeps the object Names clean. The
generated files are called exactly what RADO's are -- "SCS Lead Electrode 1.stl",
"SCS Lead Insulator.stl" -- so importing them while RADO's bodies were still
present made FreeCAD uniquify the new Names to SCS_Lead_Electrode_001..004 (it
strips the trailing digits before appending a 3-digit counter) while 5-8, which
collided with nothing, kept SCS_Lead_Electrode_5..8. Those two runs of numbers
alphabetised around RADO's _1..4 and made the tree read as a 12-contact lead
with four contacts greyed out. With RADO's five bodies gone before the import,
the eight contacts land as SCS_Lead_Electrode_1..8 and the sheath as
SCS_Lead_Insulator: contiguous, in physical order, and the contact number in the
Name means what it says. check_names() below asserts exactly that.

NOTE for anyone comparing against a variant built before 2026-09-10: those
documents were built the old way and their contacts still carry the uniquified
Names (_001..004, _5..8). Nothing keys on the digits -- tissue_map.yaml matches
on the "SCS Lead Electrode" prefix, which survives either way -- but a rebuild
by this script will not reproduce the old Names.

Renaming the STLs to dodge the filename collision would break those
tissue_map.yaml patterns, so it is not done; apply_colors.py matches them
against the object Name.

    python3 src/freecad/make_lead_variants.py --dry-run       # no FreeCAD needed
    freecadcmd src/freecad/make_lead_variants.py              # writes both variants

WARNING: that freecadcmd line is only safe on an UNCOLOURED base document. A
document saved by freecadcmd is written without GuiDocument.xml, so every
ShapeAppearance blob -- every tissue colour and transparency -- is dropped
silently (verified on FreeCAD 26.3.0, git 48502). The base document now has 245
of them and each variant 254, so rebuilding a variant this way costs a full
apply_colors.py pass in the GUI afterwards. See apply_labels.py's docstring.

This one does NOT need the Gui layer -- Visibility is an App-level property and
mesh import is App-level too -- so unlike apply_colors.py it runs fine under
plain freecadcmd. Colour the results afterwards with apply_colors.py, which does
need a running GUI; see its docstring.

Options come from MAKE_LEAD_VARIANTS_ARGS under any FreeCAD interpreter, for the
reason apply_labels.py documents: FreeCAD eats the command line itself. Output
goes to a report file because freecadcmd swallows print().
"""
import argparse
import os
import shlex
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
DEFAULT_BASE = os.path.join(REPO, "NBF_RADO-SCS.FCStd")
DEFAULT_LEADS = os.path.join(HERE, "generated_leads")
DEFAULT_REPORT = os.path.join(HERE, "make_lead_variants_report.txt")

# variant -> (directory under generated_leads/, how its bodies are labelled)
VARIANTS = {
    "dorsal":  ("dorsal_z110_8c",  "SCS 8c dorsal"),
    "ventral": ("ventral_z110_8c", "SCS 8c ventral"),
}

# RADO's original 4-contact DRG lead, deleted from every variant. Matched on
# Name, which is stable; Labels are apply_labels.py's and are not load-bearing.
RADO_LEAD = ("SCS_Lead_Electrode_1", "SCS_Lead_Electrode_2", "SCS_Lead_Electrode_3",
             "SCS_Lead_Electrode_4", "SCS_Lead_Insulator")

# What the study lead's nine bodies must be called once RADO's are gone.
EXPECTED_NAMES = tuple("SCS_Lead_Electrode_%d" % i for i in range(1, 9)) + ("SCS_Lead_Insulator",)


def script_args():
    """Arguments meant for this script; see apply_colors.script_args."""
    if os.path.basename(sys.argv[0]).lower().startswith("freecad"):
        return shlex.split(os.environ.get("MAKE_LEAD_VARIANTS_ARGS", ""))
    return sys.argv[1:]


def lead_files(lead_dir):
    """The nine STLs of one generated lead, insulator last so it imports under the contacts."""
    stls = sorted(f for f in os.listdir(lead_dir) if f.lower().endswith(".stl"))
    contacts = [f for f in stls if "Electrode" in f]
    insulators = [f for f in stls if "Insulator" in f]
    if len(contacts) != 8 or len(insulators) != 1:
        raise ValueError("%s: expected 8 contacts + 1 insulator, got %d + %d"
                         % (lead_dir, len(contacts), len(insulators)))
    return contacts + insulators


def drop_rado_lead(doc, say):
    """Delete RADO's four contacts and its insulator from `doc`. Idempotent.

    A body is removed from its tissue group first. App::DocumentObjectGroup owns
    its children through a PropertyLinkList, and removing the object without
    removing the link is how a group ends up holding a dangling entry.
    """
    dropped, absent = [], []
    for name in RADO_LEAD:
        obj = doc.getObject(name)
        if obj is None:                      # already gone: a rerun, or a base
            absent.append(name)              # document that never had it
            continue
        parent = obj.getParentGroup() if hasattr(obj, "getParentGroup") else None
        if parent is not None:
            parent.removeObject(obj)
        dropped.append("%s (%s)" % (name, obj.Label))
        doc.removeObject(name)
    say("deleted:   RADO's 4-contact DRG lead, %d bodies -- %s",
        len(dropped), ", ".join(dropped) or "none")
    if absent:
        say("           already absent: %s", ", ".join(absent))
    return len(dropped)


def check_names(added, say):
    """Confirm the imported bodies got the clean Names, i.e. nothing was uniquified."""
    got = tuple(o.Name for o in added)
    if got == EXPECTED_NAMES:
        say("names:     SCS_Lead_Electrode_1..8 + SCS_Lead_Insulator, no uniquifier suffix")
        return 0
    say("ERROR: unexpected object Names after import -- something was still")
    say("       holding those Names when the STLs were read.")
    say("       expected %s", ", ".join(EXPECTED_NAMES))
    say("       got      %s", ", ".join(got))
    return 1


def label_for(prefix, filename):
    """Readable Label for one imported lead body, in apply_labels.py's house style.

    The contact number is ZERO-PADDED ("contact 01".."08") on purpose. FreeCAD's
    tree can be sorted alphabetically, and the eight contacts share the group
    with RADO's four, so an unpadded "contact 1".."8" would sort 1, 2, ... 8 only
    by luck and would interleave with anything else in the group. Padded, the
    eight sort as one contiguous block in physical order (contact 01 is the
    caudal end, z~96 mm; contact 08 the rostral end, z~124 mm). RADO's own four
    keep single digits and are labelled "RADO DRG lead contact 1 (original,
    hidden in variants)" by body_aliases.yaml, so the two leads can no longer be
    confused in the tree -- which is exactly what happened when both were called
    "SCS lead contact N".
    """
    stem = os.path.splitext(filename)[0]
    if "Insulator" in stem:
        return "%s lead insulator" % prefix
    return "%s lead contact %02d" % (prefix, int(stem.rsplit(" ", 1)[-1]))


def build(variant, args, say):
    """Copy the base document, import one generated lead into it, save. Returns 0 on success."""
    import shutil
    import FreeCAD
    import Mesh

    subdir, prefix = VARIANTS[variant]
    lead_dir = os.path.join(args.leads, subdir)
    stls = lead_files(lead_dir)
    out = os.path.join(REPO, "NBF_RADO-SCS_%s.FCStd" % variant)

    if os.path.exists(out):
        bak = out + ".prelead.bak"
        n = 1
        while os.path.exists(bak):
            n += 1
            bak = "%s.prelead%d.bak" % (out, n)
        shutil.copy2(out, bak)
        say("backup:    %s", os.path.basename(bak))
    shutil.copy2(args.base, out)
    say("copied:    %s -> %s", os.path.basename(args.base), os.path.basename(out))

    doc = FreeCAD.openDocument(out)
    say("opened:    %s, %d objects", doc.Name, len(doc.Objects))

    # Delete BEFORE importing: it is what frees the Names the generated bodies
    # should have, and it is why they come out as _1..8 instead of _001..004
    # plus _5..8. See the module docstring.
    drop_rado_lead(doc, say)
    before = len(doc.Objects)

    # Mesh.insert reads the file straight into the document's own frame; there is
    # no placement argument and none is wanted -- see the module docstring.
    for fn in stls:
        Mesh.insert(os.path.join(lead_dir, fn), doc.Name)
    added = doc.Objects[before:]
    if len(added) != len(stls):
        say("ERROR: imported %d files but the document gained %d objects",
            len(stls), len(added))
        return 1
    if check_names(added, say):
        return 1

    say("")
    say("%-28s %-24s %s", "IMPORTED FILE", "OBJECT NAME", "LABEL")
    for fn, obj in zip(stls, added):
        obj.Label = label_for(prefix, fn)
        say("%-28s %-24s %s", fn, obj.Name, obj.Label)

    doc.recompute()
    doc.save()
    say("saved:     %s, %d objects", out, len(doc.Objects))
    FreeCAD.closeDocument(doc.Name)
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default=DEFAULT_BASE)
    ap.add_argument("--leads", default=DEFAULT_LEADS)
    ap.add_argument("--report", default=DEFAULT_REPORT)
    ap.add_argument("--variant", default="both", choices=["dorsal", "ventral", "both"])
    ap.add_argument("--dry-run", action="store_true",
                    help="report the plan; touches neither the documents nor FreeCAD")
    args = ap.parse_args(script_args())

    out = []
    def say(fmt, *a):
        out.append(fmt % a if a else fmt)

    wanted = list(VARIANTS) if args.variant == "both" else [args.variant]
    say("mode:      %s", "DRY RUN" if args.dry_run else "WRITE")
    say("base:      %s", args.base)
    say("variants:  %s", ", ".join(wanted))
    say("")

    rc = 0
    for variant in wanted:
        subdir, prefix = VARIANTS[variant]
        lead_dir = os.path.join(args.leads, subdir)
        stls = lead_files(lead_dir)
        say("=== %s ===", variant)
        say("lead:      %d STLs from %s", len(stls), os.path.relpath(lead_dir, REPO))
        if args.dry_run:
            for fn in stls:
                say("   %-28s -> Label %r", fn, label_for(prefix, fn))
            say("   would delete RADO's DRG lead: %s", ", ".join(RADO_LEAD))
            say("   would then import as: %s", ", ".join(EXPECTED_NAMES))
            say("   would write NBF_RADO-SCS_%s.FCStd", variant)
        else:
            rc |= build(variant, args, say)
        say("")

    say("RESULT: %s, %d variant(s)",
        "dry run OK" if args.dry_run else ("OK" if rc == 0 else "FAILED"), len(wanted))
    with open(args.report, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    return rc


def run_as_freecadcmd_script():
    """True when a FreeCAD interpreter was handed THIS file to run; see apply_labels.py."""
    if len(sys.argv) < 2 or not os.path.basename(sys.argv[0]).lower().startswith("freecad"):
        return False
    return os.path.abspath(sys.argv[1]) == os.path.abspath(__file__)


if __name__ == "__main__":
    sys.exit(main())
elif run_as_freecadcmd_script():
    main()
