#!/usr/bin/env python3
"""Build the dorsal and ventral 8-contact-lead variants of NBF_RADO-SCS.FCStd.

Each variant is a byte copy of the base document plus the nine STLs generated by
make_scs_lead.py (8 contacts + 1 insulator) from
src/freecad/generated_leads/<variant>_z110_8c/.

The lead STLs are already in the base model's coordinate frame -- make_scs_lead.py
swept them along the measured epidural centreline, and the placement was checked
at 100% of sampled vertices inside epidural fat and 0% in dura -- so they are
imported with NO transform of any kind. Anything that moved them would silently
invalidate that check.

RADO's own 4-contact DRG lead is LEFT IN PLACE and only hidden (Visibility =
False). Deleting it is a modelling decision about what the published RADO-SCS
model should still contain, and that is Mohamed's to make, not this script's.
It is still in the tree, still in the Ansys name selections, and one click from
being visible again.

Note what happens to the new objects' Names. The generated files are called
exactly what RADO's are -- "SCS Lead Electrode 1.stl", "SCS Lead Insulator.stl" --
so the Names those sanitize to are already taken in the base document and
FreeCAD uniquifies them. It does that by stripping the trailing digits off the
base name before appending a 3-digit counter, so contacts 1-4 land as
SCS_Lead_Electrode_001..004 (NOT _1001) while 5-8, which collide with nothing,
keep SCS_Lead_Electrode_5..8. The contact number in the Name is therefore not
reliable -- the Label is where it lives, and the Labels set below are also what
tells the 8-contact lead apart from RADO's hidden 4-contact one in the tree.

Renaming the STLs to dodge the collision would break the tissue_map.yaml
patterns that give the contacts their silver and the insulator its near-black,
so it is not done; apply_colors.py matches those patterns against the object
Name, where "SCS Lead Electrode" survives the uniquifier intact.

    python3 src/freecad/make_lead_variants.py --dry-run       # no FreeCAD needed
    freecadcmd src/freecad/make_lead_variants.py              # writes both variants

This one does NOT need the Gui layer -- Visibility is an App-level property and
mesh import is App-level too -- so unlike apply_colors.py it runs fine under
plain freecadcmd. Colour the results afterwards with apply_colors.py, which does
need a running GUI; see its docstring.

Options come from MAKE_LEAD_VARIANTS_ARGS under any FreeCAD interpreter, for the
reason apply_labels.py documents: FreeCAD eats the command line itself. Output
goes to a report file because freecadcmd swallows print().
"""
import argparse
import os
import shlex
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
DEFAULT_BASE = os.path.join(REPO, "NBF_RADO-SCS.FCStd")
DEFAULT_LEADS = os.path.join(HERE, "generated_leads")
DEFAULT_REPORT = os.path.join(HERE, "make_lead_variants_report.txt")

# variant -> (directory under generated_leads/, how its bodies are labelled)
VARIANTS = {
    "dorsal":  ("dorsal_z110_8c",  "SCS 8c dorsal"),
    "ventral": ("ventral_z110_8c", "SCS 8c ventral"),
}

# RADO's original 4-contact DRG lead, hidden but kept. Matched on Name, which is
# stable; Labels are apply_labels.py's and are not load-bearing.
RADO_LEAD = ("SCS_Lead_Electrode_1", "SCS_Lead_Electrode_2", "SCS_Lead_Electrode_3",
             "SCS_Lead_Electrode_4", "SCS_Lead_Insulator")


def script_args():
    """Arguments meant for this script; see apply_colors.script_args."""
    if os.path.basename(sys.argv[0]).lower().startswith("freecad"):
        return shlex.split(os.environ.get("MAKE_LEAD_VARIANTS_ARGS", ""))
    return sys.argv[1:]


def lead_files(lead_dir):
    """The nine STLs of one generated lead, insulator last so it imports under the contacts."""
    stls = sorted(f for f in os.listdir(lead_dir) if f.lower().endswith(".stl"))
    contacts = [f for f in stls if "Electrode" in f]
    insulators = [f for f in stls if "Insulator" in f]
    if len(contacts) != 8 or len(insulators) != 1:
        raise ValueError("%s: expected 8 contacts + 1 insulator, got %d + %d"
                         % (lead_dir, len(contacts), len(insulators)))
    return contacts + insulators


def label_for(prefix, filename):
    """Readable Label for one imported lead body, in apply_labels.py's house style."""
    stem = os.path.splitext(filename)[0]
    if "Insulator" in stem:
        return "%s lead insulator" % prefix
    return "%s lead contact %s" % (prefix, stem.rsplit(" ", 1)[-1])


def build(variant, args, say):
    """Copy the base document, import one generated lead into it, save. Returns 0 on success."""
    import shutil
    import FreeCAD
    import Mesh

    subdir, prefix = VARIANTS[variant]
    lead_dir = os.path.join(args.leads, subdir)
    stls = lead_files(lead_dir)
    out = os.path.join(REPO, "NBF_RADO-SCS_%s.FCStd" % variant)

    if os.path.exists(out):
        bak = out + ".prelead.bak"
        n = 1
        while os.path.exists(bak):
            n += 1
            bak = "%s.prelead%d.bak" % (out, n)
        shutil.copy2(out, bak)
        say("backup:    %s", os.path.basename(bak))
    shutil.copy2(args.base, out)
    say("copied:    %s -> %s", os.path.basename(args.base), os.path.basename(out))

    doc = FreeCAD.openDocument(out)
    before = len(doc.Objects)
    say("opened:    %s, %d objects", doc.Name, before)

    # Mesh.insert reads the file straight into the document's own frame; there is
    # no placement argument and none is wanted -- see the module docstring.
    for fn in stls:
        Mesh.insert(os.path.join(lead_dir, fn), doc.Name)
    added = doc.Objects[before:]
    if len(added) != len(stls):
        say("ERROR: imported %d files but the document gained %d objects",
            len(stls), len(added))
        return 1

    say("")
    say("%-28s %-24s %s", "IMPORTED FILE", "OBJECT NAME", "LABEL")
    for fn, obj in zip(stls, added):
        obj.Label = label_for(prefix, fn)
        say("%-28s %-24s %s", fn, obj.Name, obj.Label)

    hidden = []
    for name in RADO_LEAD:
        obj = doc.getObject(name)
        if obj is None:
            say("WARNING: %s not in the base document", name)
            continue
        obj.Visibility = False
        hidden.append(obj.Label)
    say("")
    say("hidden (kept, not deleted): RADO's 4-contact DRG lead -- %s", ", ".join(hidden))

    doc.recompute()
    doc.save()
    say("saved:     %s, %d objects", out, len(doc.Objects))
    FreeCAD.closeDocument(doc.Name)
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default=DEFAULT_BASE)
    ap.add_argument("--leads", default=DEFAULT_LEADS)
    ap.add_argument("--report", default=DEFAULT_REPORT)
    ap.add_argument("--variant", default="both", choices=["dorsal", "ventral", "both"])
    ap.add_argument("--dry-run", action="store_true",
                    help="report the plan; touches neither the documents nor FreeCAD")
    args = ap.parse_args(script_args())

    out = []
    def say(fmt, *a):
        out.append(fmt % a if a else fmt)

    wanted = list(VARIANTS) if args.variant == "both" else [args.variant]
    say("mode:      %s", "DRY RUN" if args.dry_run else "WRITE")
    say("base:      %s", args.base)
    say("variants:  %s", ", ".join(wanted))
    say("")

    rc = 0
    for variant in wanted:
        subdir, prefix = VARIANTS[variant]
        lead_dir = os.path.join(args.leads, subdir)
        stls = lead_files(lead_dir)
        say("=== %s ===", variant)
        say("lead:      %d STLs from %s", len(stls), os.path.relpath(lead_dir, REPO))
        if args.dry_run:
            for fn in stls:
                say("   %-28s -> Label %r", fn, label_for(prefix, fn))
            say("   would hide: %s", ", ".join(RADO_LEAD))
            say("   would write NBF_RADO-SCS_%s.FCStd", variant)
        else:
            rc |= build(variant, args, say)
        say("")

    say("RESULT: %s, %d variant(s)",
        "dry run OK" if args.dry_run else ("OK" if rc == 0 else "FAILED"), len(wanted))
    with open(args.report, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    return rc


def run_as_freecadcmd_script():
    """True when a FreeCAD interpreter was handed THIS file to run; see apply_labels.py."""
    if len(sys.argv) < 2 or not os.path.basename(sys.argv[0]).lower().startswith("freecad"):
        return False
    return os.path.abspath(sys.argv[1]) == os.path.abspath(__file__)


if __name__ == "__main__":
    sys.exit(main())
elif run_as_freecadcmd_script():
    main()
